In [64]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
df=pd.read_csv('data.csv')
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [65]:
df.country.values

array(['USA', 'USA', 'USA', ..., 'USA', 'USA', 'USA'], dtype=object)

In [66]:
df1=df.drop(['date','sqft_lot','waterfront','statezip','street','country'],axis='columns')
df1.head()

,price,bedrooms,bathrooms,sqft_living,floors,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city
0,313000.0,3.0,1.50,1340,1.5,0,3,1340,0,1955,2005,Shoreline
1,2384000.0,5.0,2.50,3650,2.0,4,5,3370,280,1921,0,Seattle
2,342000.0,3.0,2.00,1930,1.0,0,4,1930,0,1966,0,Kent
3,420000.0,3.0,2.25,2000,1.0,0,4,1000,1000,1963,0,Bellevue
4,550000.0,4.0,2.50,1940,1.0,0,4,1140,800,1976,1992,Redmond

In [67]:
df1.floors=df1.floors.round()
df1.bathrooms=df1.bathrooms.round()
df1.head()

,price,bedrooms,bathrooms,sqft_living,floors,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city
0,313000.0,3.0,2.0,1340,2.0,0,3,1340,0,1955,2005,Shoreline
1,2384000.0,5.0,2.0,3650,2.0,4,5,3370,280,1921,0,Seattle
2,342000.0,3.0,2.0,1930,1.0,0,4,1930,0,1966,0,Kent
3,420000.0,3.0,2.0,2000,1.0,0,4,1000,1000,1963,0,Bellevue
4,550000.0,4.0,2.0,1940,1.0,0,4,1140,800,1976,1992,Redmond

In [68]:
df1.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
floors           0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
city             0
dtype: int64

In [69]:
df1.shape

(4600, 12)

In [70]:
df1.price.describe()

count    4.600000e+03
mean     5.519630e+05
std      5.638347e+05
min      0.000000e+00
25%      3.228750e+05
50%      4.609435e+05
75%      6.549625e+05
max      2.659000e+07
Name: price, dtype: float64

In [71]:
df1 = df1.drop(df1[df1['price'] == 0].index, axis=0)
df1.shape

(4551, 12)

In [72]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1.city=le.fit_transform(df1.city)
df1.head()

,price,bedrooms,bathrooms,sqft_living,floors,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city
0,313000.0,3.0,2.0,1340,2.0,0,3,1340,0,1955,2005,36
1,2384000.0,5.0,2.0,3650,2.0,4,5,3370,280,1921,0,35
2,342000.0,3.0,2.0,1930,1.0,0,4,1930,0,1966,0,18
3,420000.0,3.0,2.0,2000,1.0,0,4,1000,1000,1963,0,3
4,550000.0,4.0,2.0,1940,1.0,0,4,1140,800,1976,1992,31

In [73]:
xtr,xt,ytr,yt=train_test_split(df1.drop(['price'],axis='columns'),df1.price,test_size=0.2)
xtr.shape

(3640, 11)

In [74]:
xt.shape

(911, 11)

In [75]:
model=LinearRegression()
model.fit(xtr,ytr)
model

LinearRegression()

In [49]:
model.predict(xt)

array([ 531818.91154743,  525354.75827056,  709372.69799572,
       1428252.68438692,  611694.59281359,  364260.49187936,
        663913.17078333,  368065.6640515 ,  588764.06797763,
        833697.36491469,  457261.50278828,  310284.8623144 ,
        329722.27461611,  633196.5087518 ,  344896.49374065,
        293699.25782807,  558561.51684558,  390111.83352278,
        771753.03196039,  461947.94585761,  490160.88460318,
        656490.10909354, 1103082.80766898,  844363.71112915,
        786272.42917633,  287387.59694881,  487338.58395133,
        723990.52437607,  401411.22145401,  434040.56627141,
        614341.37021129, 1374667.71043997,  684366.98322184,
        428416.393853  ,  455269.56864672,  359995.53136948,
        671372.38185992,  572073.02900408,  847603.971357  ,
        499011.43990281,  683110.52053416,  465517.70670433,
        177036.9520965 ,  499973.83572807,  488496.98319237,
       1059889.4642613 ,  518753.26201931,  308360.60092452,
        309759.78070386,  608515.59558395,  609626.1150627 ,
       1081032.76087857,  375592.34687108, 1604444.71084465,
        650907.73695272,  323408.69826959, 1121319.86901354,
        541374.95856387,  438695.0009093 ,  854974.69944003,
        630286.16960035,  406437.10585267,  538419.26932925,
        645178.09479596, 1064956.95310267,  710365.27077572,
        400613.64582781,  758901.2057819 ,  778126.80617833,
        547015.48219399,  479300.993926  ,  507299.05313976,
        794091.81409353,  390053.5604408 ,  178218.79067483,
        501630.77677627,  218865.36415611,  229207.50276322,
        206594.50690411,  332806.10678548,  620930.60814153,
        621921.43601832,  588962.37859567,  446197.0949805 ,
       1137170.08629544,  217108.71476666,  237412.94586909,
        789027.02740175,  468900.03621545,  613624.93276234,
        433973.47771003, 1384006.04541589,  672121.07216198,
        535252.0341908 ,  260774.61554525,  306204.08648202,
        525576.84784923, 1727133.08439995,  522525.52056724,
        360773.60879161,  512939.75797846,  366344.07373198,
        541694.76046854,  418190.02066297,  488405.64815367,
        428102.82165939,  291115.51361051,  997913.72246768,
        938950.91948134,  558716.35583097,  350846.83093396,
        623405.074438  ,  568363.93631087,  488808.60954993,
        680633.90730818,  379848.5044643 ,  423485.3645843 ,
        545957.15220266,  414587.79817272,  414517.02210059,
        704324.60527954,  707152.0647125 ,  779711.28830698,
        350077.70730046,  438628.40694816,  531047.51632929,
        767974.27319947,  292050.83077893,  951398.05448766,
        592650.63824556,  371782.55726902,  635173.30258055,
       1035429.24040869,  361823.76050628,  487386.51298295,
        235266.91344173,  493798.97828947, 1110227.60602923,
        284598.80646712,  839683.31284895,  604076.59989927,
        462724.66670595,  487133.8737291 ,  175766.40326459,
       1010600.35696972,  281166.77957014,  636737.80730374,
        393250.64500827,  520265.68016758,  471188.03462288,
        866065.20536244,  872016.77468998,  558220.08885078,
        325189.630677  ,  273288.31565555,  499521.07889668,
        591797.41585281,  672875.29327641,  596295.23014224,
        203825.4156977 ,  759630.15731253, 1034604.8641329 ,
        495652.1666654 ,  298593.29815264,  417645.05261149,
        414251.66676127,  796748.69322748,  181750.36792137,
        957020.56778425,  275103.53943856,  627245.72960493,
        766606.13594265,  426591.37892863,  510775.3616303 ,
        611956.96332716,  176966.88024465,  594531.99926995,
        461243.30840479,  792970.84301981,  386503.76812846,
        359965.86294654, 1217379.93008606,  887018.67853019,
        532454.11442319, 1030902.18329661,  708681.61578699,
        280869.8005873 ,  297129.65537152,  502520.1376948 ,
        551348.3360228 ,  807921.62703015,  361454.33063304,
        669118.86790569,  530339.79007163,  408758.26641732,
        499669.76572765,  642350.35059734,  386945.72074243,
        478943.2345538 ,  468856.08986007,  510578.90188119,
        353075.4844399 ,  573765.34149045,  403828.57193754,
        685276.06033375,  777091.16435357,  497838.73102948,
        989817.87280942,  942451.53310882,  435528.60705496,
        309462.99860233,  529491.53286392,  409233.82994914,
        348431.68938658,  417337.47931651,  776799.95261438,
        255481.94569564,  604932.79725135,  485596.82706699,
        466173.32980122,  770784.21734075,  530626.25987934,
        244702.65635221,  485178.67043078,  491517.11274362,
        599504.54567185,  450759.16279022, 1089449.80861681,
        640722.23410996,  606676.4003171 ,  364194.63225364,
        378113.83592267, 1053880.70823965,  461160.43401082,
        412811.23055263,  513142.64096589,  358155.55424194,
        581584.84012685,  663151.15871053,  422911.15989903,
        385322.53576842,  446622.63937222,  803721.27169431,
        309510.88133785,  424185.87090004,  193982.93505259,
        645530.68042832,  381575.21106705,  659043.25134432,
        459805.81215146,  445226.16253816,  506425.19412402,
        401425.58677087,  320317.69751566,  172925.5832551 ,
        734140.3404455 ,  246592.46195852,  636802.7401047 ,
        458907.49758611,  796355.38944458,  540154.2873738 ,
       1356314.94800238,  521388.58115621,  672600.18265999,
        588927.44764369,  544368.83405702,  320342.54596826,
       1018333.74846687,  261432.12002589,  411317.02071794,
        404718.09159045,  444408.15500551, 1593781.85539172,
        976930.58692081,  528969.03013331, 1033168.54941456,
        388078.14840352,  283123.8088377 ,  675015.27416133,
        513847.99757553, 1273437.25364852,  398604.14695286,
        540104.48817501,  364294.92613254,  417810.78471941,
        460271.5199768 , 1007054.4295481 ,  575616.23158191,
        469213.09313822,  387921.1683708 ,  583236.74762321,
        822329.25826877,  417298.88403405,  426790.4508111 ,
        543584.33789399,  426116.23312231,  390541.53645655,
        740248.24865707,  588698.64657551,  349094.75411686,
        361152.27049457,  344138.31128972, 2748745.73711221,
        204936.53628653,  439743.4979921 ,  402408.43628818,
        795659.0478426 ,  329149.20229117,  775259.69394497,
        439324.63900287,  297583.18447358,  314796.44982445,
        795933.47374096,  516547.82233156,  333465.54892888,
        590508.8388125 ,  395221.40408636,  658633.45430719,
        308244.37619742,  307405.85825953,  557453.49351276,
        871152.5856614 ,  493002.12866818,  324585.35498696,
        216427.13244162,  320009.95178688,  339559.97364007,
        708542.06115664,  319906.16926382,  275027.37711126,
        746920.77656903,  605535.74283896,  633358.32503487,
        210530.70544655,  460017.40223462,  446217.10700267,
        357213.7559136 ,  422015.67823397,  757340.66949569,
       1074609.66946179,  921360.0672334 ,  694514.5095274 ,
        510221.48843859,  515522.82360365,  505956.92779661,
        713439.12680606,  393185.71220731,  541999.95201568,
        421439.08635358,  493709.03131699,  374886.06767312,
        484120.74051988,  894350.87802381,  272330.47967029,
        469574.39783251, 1034908.95999703,  377574.60093573,
        498738.63170277, 1269097.92087231,  610420.60990992,
        560603.03962338,  242135.56729763,  447304.01743379,
        383220.9417946 ,  438538.58360726,  791280.0193005 ,
        863356.10762147,  410802.8238762 ,  504335.43849046,
        621531.47993158,  578099.04892632,  819674.96779925,
        315318.95771661,  604783.42036179,  656047.12010062,
        762114.14384515,  298225.5464626 ,  268202.05820093,
        565957.06071694,  708785.02980868,  412227.75987714,
        394787.51005671,  311792.80135665,  777755.26183228,
        277816.80019089,  555115.34989624,  134291.39249423,
        481373.96388395,  320306.07690549,  707152.0647125 ,
        808699.68757505,  703641.53904853,  234870.00823677,
       1130071.83313606,  707543.92023569,  355743.4311121 ,
        791575.41849203,  683937.94462636,  541825.60520029,
        255724.5665596 ,  931887.78340534,  299095.96834418,
        513010.77876082,  216688.06135709,  600760.02215564,
        464278.63983655,  588579.63519555,  476678.02080178,
        650269.83241235,  506708.43656525,  522148.98423371,
        245433.3574657 ,  397719.72779715,  817592.28220278,
        383868.44259059,  451729.45119405,  387698.09952571,
       1103731.78743357,  663671.4130035 ,  791495.28650759,
       1063778.93805544,  363091.73090486,  325295.70525964,
        424884.39745823,  504756.27756392,  458309.07105839,
        641759.08270476,  416056.12161124,  718022.63816924,
        284340.01441658,  680939.22122406,  605399.76566601,
       1410131.46721169,  647819.80523179,  367532.26872067,
       1039634.22000992,  370676.4580503 ,  561332.11497241,
       1217150.09141158,  359884.18336232,  500192.69586392,
        343194.21400671,  909206.83496564,  453316.81870617,
       1110114.33005052,  438906.70860511,  363266.59061075,
       1035217.50957347, 1001891.73125297,  510125.58279887,
        279710.42783478,  533995.43228508,  467810.90302162,
        579944.87598356,  457205.07035779,  653958.29032479,
       1049789.26524811,  435039.70530392,  566914.77542394,
        462161.52618693,  300555.17831995, 1253909.61633609,
        548811.74883184,  623341.42818443,  670138.57029503,
        505512.94689009,  541421.39726779,  526082.43805727,
        467767.4083335 ,  577778.37600762,  282179.98811447,
        564184.94531183,  579098.77116713,  590254.73761398,
        398169.67288981,  615948.46830405,  562863.30293921,
        623470.744872  ,  544063.10748873,  337832.36720898,
        547344.91522542,  539745.85856099,  947445.41147172,
        413554.62322894,  709185.67578304,  437136.1081686 ,
        609886.88646291,  673558.50491536,  623866.88368737,
        897136.09810343,  596224.82754905,  240974.26418271,
        843286.78043293,  204105.70393971, 1057688.42639063,
       1030138.6594178 ,  431943.97809876,  644898.5344273 ,
        440647.69981888,  592275.571484  ,  608967.11041368,
        329397.13757358,  641827.76527284,  369456.53011055,
        937329.01840123,  471076.91196049,  994932.71168333,
        827668.63131525,  578590.66934371,  527474.917414  ,
        970813.7702082 ,  367885.54789622,  272914.23836402,
        287932.57802584,  229799.40544701,  548573.50827194,
        672216.79019706,  343973.85346026,  440513.61261103,
       1401526.2664297 ,  534852.79932603,  284703.77293782,
        837320.30485035,  688165.88268328,  391551.92713236,
        812789.08350796,  512808.75034029,  549138.25793576,
        292149.84028495,  275314.66921222,  368225.2129422 ,
        464694.5246583 ,  615547.72441192,  517723.95016202,
        495944.92743804,  393095.69817035,  265456.46312283,
        495499.71503096,  359783.47766339,  239246.95683128,
        534525.25093502,  278873.76970311,  203445.30367251,
        431983.22995555,  423275.78759347,  684039.35029555,
        506309.69383896,  309903.51461748,  946900.08792036,
        284439.45170104,  826783.75864686,  615063.77127973,
        241956.31732739,  848416.65088926,  499935.1810146 ,
        442028.62285949,  890387.2473993 ,  641565.27621547,
        305556.1688373 ,  474362.91188602,  549400.05843282,
        451421.81994283, 1116205.17325225,  310001.07145986,
        640111.1396312 ,  376254.27158249,  502859.5584787 ,
        569185.09606506,  443122.35616293,  698615.20082948,
        821693.39066887,  346938.90591703,  597636.84321102,
        415275.07737602,  384899.82479055,  526075.22942965,
        620847.98300724,  293910.52597045,  372903.91529171,
        886466.36521622,  465018.80413344,  621660.45767405,
        513284.25072473,  468044.79520531,  182743.80506245,
        409061.44819765,  507329.82153052,  418759.59443334,
        476396.46055924,  595141.12727345,  430433.38120542,
        840783.82258422, 1048911.8836515 ,  439149.19359641,
        322312.68575597, 1375520.5884916 ,  333344.32052182,
        224894.97854804,  510259.60269511,  461223.41504059,
        535092.99825943,  676926.28583513,  484329.5846681 ,
        284748.98507865, 1463828.95577143,  589896.13292655,
        534249.48196666,  532161.59867157,  436131.58088775,
        681235.39658067,  504815.99785457,  706417.80487972,
        813434.24122098,  310232.7000135 ,  701409.37922272,
        439267.48989185,  474945.18845978,  286601.10351025,
        289294.84367807,  733875.68638896,  438719.52877061,
        542973.12372471,  320772.94027416,  271733.77795845,
        399285.7841467 ,  582312.73641801,  814330.088067  ,
        298374.92806201,  487018.35028417,  509823.94938552,
       1089984.64656009,  253100.57010722,  564508.77886553,
        451650.20704543,  241750.90196285,  492623.83596051,
        630629.51791497,  210898.12703413, 1136474.88345981,
        692487.75964084,  436072.8697593 ,  324547.62237578,
        327752.50516389,  503062.85854991,  607114.94554256,
        558624.68581501,  547804.15486081,  476418.17105906,
        231886.15636165,  629333.52144699,  616764.3578666 ,
        364126.1638888 ,  425345.22294582,  436722.62797561,
        437050.02052385,  366763.76921761,  603477.56357735,
        884057.45173707,  581091.17169815,  293523.49238118,
        398148.07322099,  660349.85129777,  516549.19791223,
       1486035.04122976, 1544278.52045483,  936040.34773178,
        430905.47174017,  611837.11731842,  244156.11004164,
        526713.62800834,  412257.16556331,  313628.57823174,
        537336.2509119 ,  492573.60643195,  519341.50056165,
        786554.74791814,  542374.59551608,  536892.36104816,
       1263336.28053255,  260984.70794419,  461203.47399766,
        247478.72238487,  852473.19063974,  381687.44684442,
        473443.75350115,  154400.16124314,  517041.02090989,
        288646.37203174, 1156628.85896914,  477708.61744409,
       1586601.29571087,  703442.53543679,  396869.13165439,
        711461.96274289,  370855.06472293,  569086.66848455,
        836567.861318  ,  473973.86315191,  575346.75174881,
        293184.55786078,  377980.31808116,  523541.62456347,
       1146255.77761936,  409242.86805666,  519820.97425276,
        446969.35208237,  573677.50472068, 1465133.21828749,
        382387.38792373,  386688.59421673,  304052.14421133,
        636289.00881339,  447446.33484059,  571518.6210587 ,
        370856.33545013,  890196.20102134,  514772.24477129,
        715966.53126735,  522273.0406663 ,  620252.64391485,
        485168.4192176 ,  296472.07778291,  369847.97294913,
        436646.41673581,  549319.24324987, 1331611.14806196,
        586675.06394984,  206025.22634368,  432361.49451598,
        294097.84086313,  222414.35842744,  827993.58137648,
        303684.11517317,  168125.57269362,  937586.32191755,
        345614.53222416,  850265.32599784,  508384.01043262,
        774685.33915951,  767401.75906825,  763640.2953476 ,
        357503.67967928,  651504.60273065,  436419.23594163,
        889248.37577493,  489941.35173687,  493092.12107352,
        686061.2198136 ,  413380.77167759,  573263.49859245,
        426041.22860454,  473322.42686155,  856382.57444197,
        443409.70638415,  961536.59611411,  459204.18593848,
        266595.91087355,  312626.46521511,  656791.07807948,
        417921.31658066,  512196.01249123,  763072.85099961,
        520411.45247131,  473117.52488802,  269017.50999369,
        697767.23593095,  245101.16252001,  509996.75818687,
        310929.9852942 ,  294850.89799876,  675655.66152084,
        629058.03809453,  296819.79491278,  404833.34511628,
        344396.11979459,  379367.95063282,  912868.15238051,
        451285.30732291,  400458.67590717,  960511.42829882,
        352169.00755005,  577444.84535718,  939758.67763205,
        173570.30726597,  733220.73874765,  236747.46748087,
        746035.82734971,  555932.94006304,  339697.15427324,
        624054.63119267,  683426.4955735 ,  327622.164179  ,
        376497.84717488,  310039.11988543,  595097.22013646,
        340541.55859029,  731403.24967658,  424133.713319  ,
        280589.01723686,  825764.73094735,  430597.51232288,
        373556.63767787,  605730.54124184,  383237.45495575,
        473455.46125198,  609711.04522089,  439205.29662084,
        383923.24808326,  309070.65670527,  442754.84622107,
        399007.44583815,  597643.42994997,  427266.31048942,
        511982.85572761,  228791.72175027,  317698.53292875,
        332325.93246401,  578156.45235559,  283353.53525001,
        275363.31275821,  342881.58486177,  365417.35606521,
        675924.27111637,  591872.85804065,  429155.93388168,
        631872.66154945,  506730.58595949,  412018.77904356,
        659282.9484668 ,  675608.80969035,  672519.51964969,
        586945.36652499,  244770.29273542,  887201.80884997,
        474906.74492413,  392260.48340575,  478632.40697369,
        505901.45584146,  765310.37970831, 1339809.86200017,
        251181.38808509,  332511.56887866,  617967.74447835,
        517709.58770444,  664064.86840724,  573034.98931914,
        400160.5734946 ,  450903.42303998,  467230.08565023,
        737192.25039716,  434758.73675023,  738871.1447335 ,
        824786.2725602 ,  796312.61393715,  467634.00876352,
        663592.25869507, 1334086.06080451,  577851.76932303,
        391142.9939482 ,  400610.72727669,  322343.3396779 ,
        556053.0058017 ,  806550.12930735,  585206.82371768,
        774141.02205977,  677807.76279122,  698666.43566977,
        815023.69668959,  660075.56250532, 1040466.64966478,
        166332.82524804,  591923.58200916,  267775.76494995,
        442375.3709478 ,  429089.42714381,  294169.49800796,
        389449.42520491,  787943.36063381,  260708.17102267,
       1024890.87181685,  317215.42410002,  668356.10368684,
        754977.87091363,  360523.34749579,  424661.29002948,
        546760.00144953,  216972.77014389,  690352.74856102,
       1496875.40816475,  667889.04132067,  936959.1909129 ,
        505013.80769931,  913218.31032738,  449724.4872742 ,
        752036.15165344,  783760.39550899,  470799.73202071,
        237960.43480542,  471705.38777755,  947960.13843818,
        725122.44738112,  502168.1255882 ,  682085.88944047,
       2600370.2761035 , 1175578.78686884,  605729.13696475,
        786875.89422586,  882670.17313625,  638558.83440767,
        343267.84937047,  673462.04392953])

In [50]:
model.score(xt,yt)

0.6075766507560769